image: node:10.11.0 # can be upgraded, depending on your node version used

cache:
  paths:
  - ./node_modules/
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv public/ oldpublic/
  - mv build/ public/
  - ls public
  artifacts:
    paths:
    - public
  only:
  - master