image: node:8.11.1 # can be upgraded, depending on your node version used

cache:
  paths:
  - ./node_modules/
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - mv build/* public/
  artifacts:
    paths:
    - public
  only:
  - master